print('Welcome to the Tip Calculator.')
bill = float(input('What was the total bill?\n$'))
tip = int(input('What percentage tip would you like to give? 10, 12 or 15?\n$'))
split = int(input('How many people to split the bill?\n$'))
payment = round((bill + (bill *(tip / 100))) / split,2)
print(f'Each person will pay {payment}')